### PR TITLE
Automagically build unstable plugins

### PR DESCRIPTION
**Pull request by crobibero**

### CODE REVIEW

**Comment by Gauvino** [comment]
With this PR could we use 10.9 unstable with all the plugin ?

**Comment by crobibero** [comment]
That would be the end goal but this is still very much a work in progress

**Comment by Gauvino** [comment]
> That would be the end goal but this is still very much a work in progress

What as to be done before merging this ?

**Comment by crobibero** [comment]
This is step 1 of.. unknown. I just threw together something quickly while I was thinking about it. Highly unlikely that it will be ready for 10.9 prerelease

**Comment by crobibero** [comment]
An alternate version is now live.

**Pull request closed without merging**
